import {Transaction} from './transaction';
export let Transactions: Transaction[] = [
    {"id": 1, "date": "juice 1", "amount": "1"},
    {"id": 2, "date": "juice 2", "amount": "2"},
    {"id": 3, "date": "juice 3", "amount": "3"},
    {"id": 4, "date": "juice 4", "amount": "4"},
    {"id": 5, "date": "juice 5", "amount": "5"},
    {"id": 6, "date": "juice 6", "amount": "6"},
    {"id": 7, "date": "juice 7", "amount": "7"},
    {"id": 8, "date": "juice 8", "amount": "8"},
    {"id": 9, "date": "juice 9", "amount": "9"},
    {"id": 10, "date": "orange 1", "amount": "1"},
    {"id": 11, "date": "orange 2", "amount": "2"},
    {"id": 12, "date": "orange 3", "amount": "3"},
    {"id": 13, "date": "orange 4", "amount": "4"},
    {"id": 14, "date": "orange 5", "amount": "5"},
    {"id": 15, "date": "orange 6", "amount": "6"},
    {"id": 16, "date": "orange 7", "amount": "7"},
    {"id": 17, "date": "orange 8", "amount": "8"},
    {"id": 18, "date": "orange 9", "amount": "9"},
    {"id": 19, "date": "orange 10", "amount": "10"},
    {"id": 20, "date": "orange 11", "amount": "11"},
    {"id": 21, "date": "orange 12", "amount": "12"},
    {"id": 22, "date": "orange 13", "amount": "13"},
    {"id": 23, "date": "orange 14", "amount": "14"},
    {"id": 24, "date": "orange 15", "amount": "15"},
    {"id": 25, "date": "orange 16", "amount": "16"},
    {"id": 26, "date": "orange 17", "amount": "17"},
];